# Generated by Django 4.0.8 on 2023-01-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
