# Generated by Django 4.0.8 on 2023-01-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=255)),
                ('presenters', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('presentation_type', models.CharField(blank=True, max_length=255, null=True)),
                ('technical_topics', models.CharField(blank=True, max_length=255, null=True)),
                ('presentation_date', models.DateTimeField(blank=True, null=True)),
                ('publication_status', models.CharField(blank=True, max_length=255, null=True)),
                ('presentation_slides', models.URLField(blank=True, max_length=255, null=True)),
                ('documents', models.URLField(blank=True, max_length=255, null=True)),
                ('captions', models.URLField(blank=True, max_length=255, null=True)),
                ('presentation_video', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
