# Generated by Django 4.0.8 on 2023-01-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(default='Short description of resource'),
            preserve_default=False,
        ),
    ]
