# Generated by Django 4.0.8 on 2023-01-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_card', '0002_resource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(null=True, upload_to='resource_images/'),
        ),
    ]
