# This workflow will install Python dependencies, run the python scrapper script for the Algerian Research Hub Funding Opportunities

name: Python web scrapper

on:
  #Allow job to run manually
  workflow_dispatch:
  #Trigger the workflow on daily basis (To update the funding request page)
  #schedule:
    #schedule runs every day at 0:00 (mid-night)
    #- cron: "0 0 * * *"
    #- cron: "5 * * * *"


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x' #Version range or exact version of a python version to use, using semVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Default to x64 if not scpecified
        
    - name: Install dependencies
      run: |
        pip install requests
        pip install airtable
        pip install -r requirements-dev.txt
        
    - name: Run the python scrapper script
      run: |
        python .github/workflows/arhscrapper.py
